## C-Means
Assim como K-means, utiliza da distancia euclidiana para classificar objetos por agrupamento.  
Contudo, não agrupa de maneira absoluta, e sim, retornando um percentual.

## LIBS
- pip install scikit-fuzzy

## ERROR | skfuzzy
'imp' module not found

### Change de \_\_init__ file

```python
import os.path as osp
import functools
import warnings
import sys

try:
    import importlib.util
    importlib.import_module('nose')
except ImportError:
    def _test(doctest=False, verbose=False):
        """This would run all unit tests, but nose couldn't be
        imported so the test suite can not run.
        """
        raise ImportError("Could not load nose. Unit tests not available.")

else:
    def _test(doctest=False, verbose=False):
        """Run all unit tests."""
        import nose
        import warnings
        args = ['', pkg_dir, '--exe', '--ignore-files=^_test']
        if verbose:
            args.extend(['-v', '-s'])
        if doctest:
            args.extend(['--with-doctest', '--ignore-files=^\.',
                         '--ignore-files=^setup\.py$$', '--ignore-files=test'])
            # Make sure warnings do not break the doc tests
            with warnings.catch_warnings():
                warnings.simplefilter("ignore")
                success = nose.run('skfuzzy', argv=args)
        else:
            success = nose.run('skfuzzy', argv=args)
        # Return sys.exit code
        if success:
            return 0
        else:
            return 1

finally:
    if 'importlib' in locals():
        del importlib
    elif 'imp' in locals():
        del imp

del warnings, functools, osp, sys
```

In [79]:
import numpy as np
import skfuzzy as fuzz
from sklearn import datasets
from sklearn.metrics import confusion_matrix, accuracy_score

In [80]:
iris = datasets.load_iris()

## Criando CLUSTERS | C-means
- T -> Faz a trasnposição de uma matriz | matriz transposta
- c= -> Qtd de clusters

In [81]:
r = fuzz.cmeans(
    data=iris.data.T, c=3, m=2, error=0.005,
    maxiter=1000,
    init=None
)
r

(array([[5.00396476, 3.41411403, 1.48277452, 0.25352792],
        [5.88842335, 2.76088589, 4.36320803, 1.39693183],
        [6.77439608, 3.05220307, 5.64601482, 2.05325034]]),
 array([[9.96623633e-01, 9.75839160e-01, 9.79817204e-01, 9.67409718e-01,
         9.94470037e-01, 9.34545484e-01, 9.79482610e-01, 9.99547019e-01,
         9.30346028e-01, 9.82712862e-01, 9.68029827e-01, 9.92132151e-01,
         9.70624973e-01, 9.22939237e-01, 8.89725945e-01, 8.41298391e-01,
         9.46907624e-01, 9.96652326e-01, 9.04095142e-01, 9.79181670e-01,
         9.68586206e-01, 9.84826811e-01, 9.58645904e-01, 9.79411354e-01,
         9.66897006e-01, 9.73550402e-01, 9.94840568e-01, 9.93345634e-01,
         9.93673929e-01, 9.79503592e-01, 9.78713823e-01, 9.74350998e-01,
         9.38500553e-01, 9.04140667e-01, 9.85055834e-01, 9.84988329e-01,
         9.64171402e-01, 9.90889388e-01, 9.39656772e-01, 9.98288148e-01,
         9.94727458e-01, 8.50668924e-01, 9.52594875e-01, 9.79275130e-01,
         9.45241873e-

## Retorno Percentual

In [82]:
previsores_porcentagem = r[1]
previsores_porcentagem

array([[9.96623633e-01, 9.75839160e-01, 9.79817204e-01, 9.67409718e-01,
        9.94470037e-01, 9.34545484e-01, 9.79482610e-01, 9.99547019e-01,
        9.30346028e-01, 9.82712862e-01, 9.68029827e-01, 9.92132151e-01,
        9.70624973e-01, 9.22939237e-01, 8.89725945e-01, 8.41298391e-01,
        9.46907624e-01, 9.96652326e-01, 9.04095142e-01, 9.79181670e-01,
        9.68586206e-01, 9.84826811e-01, 9.58645904e-01, 9.79411354e-01,
        9.66897006e-01, 9.73550402e-01, 9.94840568e-01, 9.93345634e-01,
        9.93673929e-01, 9.79503592e-01, 9.78713823e-01, 9.74350998e-01,
        9.38500553e-01, 9.04140667e-01, 9.85055834e-01, 9.84988329e-01,
        9.64171402e-01, 9.90889388e-01, 9.39656772e-01, 9.98288148e-01,
        9.94727458e-01, 8.50668924e-01, 9.52594875e-01, 9.79275130e-01,
        9.45241873e-01, 9.72130815e-01, 9.76783955e-01, 9.74208519e-01,
        9.77211896e-01, 9.97071462e-01, 4.45737393e-02, 2.91970628e-02,
        3.12548016e-02, 4.92455719e-02, 2.41425365e-02, 5.735256

In [83]:
for x in range(150):
    print(
        previsores_porcentagem[0][x],
        previsores_porcentagem[1][x],
        previsores_porcentagem[2][x],
    )

0.9966236326967518 0.002304439887323789 0.001071927415924382
0.9758391596666987 0.016659550779319198 0.007501289553982199
0.9798172038823694 0.013766057837012334 0.006416738280618183
0.9674097182289624 0.02247836592050799 0.010111915850529748
0.9944700369426824 0.0037620709614964967 0.0017678920958211827
0.9345454843777558 0.04482720399192257 0.02062731163032167
0.9794826098543195 0.014010601651296105 0.006506788494384412
0.9995470192593456 0.00031171375146814365 0.00014126698918626342
0.9303460279344646 0.04774326154154 0.021910710523995385
0.9827128621232607 0.011943040964175169 0.0053440969125641245
0.9680298273499761 0.02176598824187727 0.010204184408146535
0.9921321509852399 0.005435495136389099 0.0024323538783711392
0.9706249728184714 0.020194093067737943 0.00918093411379073
0.9229392371317359 0.05181692642859701 0.02524383643966716
0.8897259448399764 0.07263248282226195 0.03764157233776179
0.8412983913965129 0.10438081390369536 0.054320794699791675
0.9469076242933556 0.035591907

## Perormance | Confusão
- axis=0 -> Buscamos as linhas

In [84]:
previsoes = previsores_porcentagem.argmax(axis=0)
confusao = confusion_matrix(iris.target, previsoes)
confusao

array([[50,  0,  0],
       [ 0, 47,  3],
       [ 0, 13, 37]], dtype=int64)

In [85]:
taxa_acerto = accuracy_score(iris.target, previsoes)
taxa_acerto

0.8933333333333333