# LIBS
- pip install keras
- pip install scikit-learn
- pip install tensorflow

In [8]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical
import numpy as np


## Separando elementos

In [5]:
data_ = datasets.load_iris()
previsores = data_.data
previsores

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

### As classes já estão num formato numérico!

In [6]:
classes = data_.target
classes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

## Transformação de dados
Transformamos as classes para o formato "dummy", pois temos uma rede neural com 3 saidas.

In [9]:
classe_dummy = to_categorical(classes)
classe_dummy

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

# Treino | Teste

In [10]:
x_treino, x_teste, y_treino, y_teste = train_test_split(
    previsores,
    classe_dummy,
    test_size=0.3,
    random_state=0
)

# Rede Neural
- Estrutura com sequencia de camadas (Sequential)
- Dense() -> Gera camadas 100% conectadas (todos os neuronios conectados)
- units= -> Qtd de neuronios
- input_dim -> Neuronios de entrada (4 variaveis independentes de Iris)
- activation -> funcao de ativação | softmax (gera probabilidades para cada saida)  
  
Como são três classes, não podemos utilizar uma função de ativação simples com retorno de 0 ou 1 por exemplo.

In [12]:
modelo = Sequential()

# camada oculta 1 + camada de entrada
modelo.add(Dense(units=5, input_dim=4))

# camada oculta 2
modelo.add(Dense(units=4))

# camada oculta 3 e função de ativação
modelo.add(Dense(units=3, activation='softmax'))

modelo.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 5)                 25        
                                                                 
 dense_2 (Dense)             (None, 4)                 24        
                                                                 
 dense_3 (Dense)             (None, 3)                 15        
                                                                 
Total params: 64 (256.00 Byte)
Trainable params: 64 (256.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


## Compilação | Treinamento
- compile() -> Parametros do modelo
- optimizer -> Otimiza os pesos
- loss -> Calcula a diferença entre valores previstos e reais, e realiza calculo para juste dos pesos
- metrics -> Analisa performance
- epochs -> Qtd de testes da rede neural
- validation_data -> Dados de teste

In [13]:
# Parametros da rede neural
modelo.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# Treinamento da rede neural
modelo.fit(
    x_treino,
    y_treino,
    epochs=1000,
    validation_data=(x_teste, y_teste)
)

Epoch 1/1000
4/4 [==============================] - 1s 47ms/step - loss: 1.3346 - accuracy: 0.6286 - val_loss: 1.0396 - val_accuracy: 0.7333
Epoch 2/1000
4/4 [==============================] - 0s 8ms/step - loss: 1.2565 - accuracy: 0.6286 - val_loss: 1.0041 - val_accuracy: 0.7556
Epoch 3/1000
4/4 [==============================] - 0s 13ms/step - loss: 1.1865 - accuracy: 0.6286 - val_loss: 0.9747 - val_accuracy: 0.7556
Epoch 4/1000
4/4 [==============================] - 0s 11ms/step - loss: 1.1202 - accuracy: 0.6286 - val_loss: 0.9519 - val_accuracy: 0.7556
Epoch 5/1000
4/4 [==============================] - 0s 9ms/step - loss: 1.0681 - accuracy: 0.6286 - val_loss: 0.9354 - val_accuracy: 0.7556
Epoch 6/1000
4/4 [==============================] - 0s 9ms/step - loss: 1.0176 - accuracy: 0.6286 - val_loss: 0.9253 - val_accuracy: 0.7556
Epoch 7/1000
4/4 [==============================] - 0s 10ms/step - loss: 0.9795 - accuracy: 0.6286 - val_loss: 0.9210 - val_accuracy: 0.7778
Epoch 8/1000
4/4

## Previsoes | Confusão

In [14]:
previsoes = modelo.predict(x_teste)

# Adaptação para o retorno em true | false
previsoes = (previsoes > 0.5)
previsoes

2/2 [==============================] - 0s 3ms/step


array([[False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False, False,  True],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [Fa

In [15]:
# Buscando maior valor de cada saida
y_teste_matrix = [np.argmax(t) for t in y_teste]
y_previsao_matrix = [np.argmax(t) for t in previsoes]

In [16]:
confusao = confusion_matrix(y_teste_matrix, y_previsao_matrix)
confusao

array([[16,  0,  0],
       [ 0, 17,  1],
       [ 0,  0, 11]])