In [1]:
import numpy as np

mt = np.array([1, 2, 3, 4, 5])
print(mt)
print(type(mt))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
mt2 = np.array([1, 2, 3, 4], dtype=np.float64)
print(mt2)
print(type(mt2))

mt3 = np.array([1, 2, 3, 4], dtype=np.int64)
print(mt3)
print(type(mt3))

[1. 2. 3. 4.]
<class 'numpy.ndarray'>
[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
mt4 = np.array([1.2, -4.6, 2.1, -69.75])
print(mt4)
mt4_2 = mt4.astype(np.int32)
print(mt4_2)

[  1.2   -4.6    2.1  -69.75]
[  1  -4   2 -69]


In [4]:
mt5 = np.array([1, 2, 3, 4])
print(mt5)
mt5_2 = mt5.astype(np.float64)
print(mt5_2)

[1 2 3 4]
[1. 2. 3. 4.]


In [5]:
mt6 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(mt6)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
vazio = np.empty([3, 2], dtype=np.int64)
print(vazio)
print('_' * 50)
zeros = np.zeros([4, 8], dtype=np.int64)
print(zeros)
print('_' * 50)
uns = np.ones([4, 2], dtype=np.int64)
print(uns)
print('_' * 50)
quadratica = np.eye(6, dtype=np.int64)
print(quadratica)

[[2 0]
 [0 0]
 [0 0]]
__________________________________________________
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
__________________________________________________
[[1 1]
 [1 1]
 [1 1]
 [1 1]]
__________________________________________________
[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [7]:
from numpy import dtype


ale = np.random.random((4))
print(ale)
print('_' * 50)
ale2 = np.random.randn((5))
print(ale2)
print('_' * 50)
ale3 = 10 * np.random.random((3, 4))
print(ale3)

[0.83334251 0.69784646 0.23961072 0.41250664]
__________________________________________________
[-0.56237125 -0.42655221 -1.18509059  0.74168994 -0.05884401]
__________________________________________________
[[4.49510357 1.23648061 3.76992167 5.02854738]
 [8.20939336 6.5461455  6.00002471 7.14878083]
 [0.31091209 6.54334216 9.45184183 6.12946108]]


In [8]:
gnr = np.random.default_rng(1)
ale4 = gnr.random((11))
print(ale4)
print('_' * 50)
ale5 = gnr.integers(10, size=(4, 4))
print(ale5)

[0.51182162 0.9504637  0.14415961 0.94864945 0.31183145 0.42332645
 0.82770259 0.40919914 0.54959369 0.02755911 0.75351311]
__________________________________________________
[[8 5 8 3]
 [4 7 1 3]
 [1 4 9 1]
 [3 4 9 2]]


In [9]:
j = np.array([12, 12, 10, 10, 1, 1, 11, 11, 13, 14, 15])
print(j)
j = np.unique(j)
print(j)



[12 12 10 10  1  1 11 11 13 14 15]
[ 1 10 11 12 13 14 15]


In [10]:
k = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(k)
print(k[0][1])
print(k.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


In [11]:
print(k.min())
print(k.max())
print(k.sum())
print(k.mean())
print(k.std())

1
9
45
5.0
2.581988897471611


In [12]:
k1 = np.array([1, 4, 9, 16, 25])
print(k1)
print(np.sqrt(k1))
print(np.exp(k1))

[ 1  4  9 16 25]
[1. 2. 3. 4. 5.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]


In [13]:
m = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(m)
print(m[4])
print(m[4:])
print(m[-3:])
print(m[::-1])

[ 1  2  3  4  5  6  7  8  9 10]
5
[ 5  6  7  8  9 10]
[ 8  9 10]
[10  9  8  7  6  5  4  3  2  1]


In [14]:
n = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(n)
print(n[0, :])
print(n[2, :])
print(n[0, ::-1])
print(n[:, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[7 8 9]
[3 2 1]
[3 6 9]


In [15]:
o = np.array([[10, 10, 10], [20, 20, 20]])
p = np.array([[10, 10, 10], [20, 20, 20]])
print(o)
print(p)
print(o + p)
print(o * p)
print('_' * 50)
o_1 = np.array([10, 10, 10])
o_2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(o_1)
print(o_2)
print(o_1 + o_2)
print(o_1 * o_2)

[[10 10 10]
 [20 20 20]]
[[10 10 10]
 [20 20 20]]
[[20 20 20]
 [40 40 40]]
[[100 100 100]
 [400 400 400]]
__________________________________________________
[10 10 10]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [16]:
q = np.arange(15).reshape((3, 5))
print(q)
print('_' * 50)
print(q.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
__________________________________________________
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [17]:
p = np.arange(15).reshape((3, 5))
print(p)
print('_' * 50)
print(p.transpose((1, 0)))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
__________________________________________________
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [18]:
r = np.random.randn(4, 4)
print(r)
z = (r > 0)
print(z)
z_1 = np.where(z > 0, 1, -1)
print(z_1)

[[-0.43705291  1.58065214 -1.71299429  0.93706037]
 [ 0.72444405  0.56680793  0.29558118 -0.15439953]
 [-0.01061627 -1.11878807  1.7557231  -0.1090467 ]
 [ 0.06923919 -0.27478315 -1.26152199 -1.21635081]]
[[False  True False  True]
 [ True  True  True False]
 [False False  True False]
 [ True False False False]]
[[-1  1 -1  1]
 [ 1  1  1 -1]
 [-1 -1  1 -1]
 [ 1 -1 -1 -1]]
